server:
  port: 8888
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: debug
spring:
  application:
    name: oauth2-server-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.100:8848
        namespace: f2e7b5c7-f463-465c-96de-de2abdd5f979
secret-key:
  rsa:
    private-key-pem: /rsa/rsa_private_key_pkcs8.pem
    public-key-pem: /rsa/rsa_public_key_pkcs8.pem