# https://openid.net/specs/openid-connect-core-1_0.html#UserInfo
GET /userinfo HTTP/1.1
Host: localhost:8888
Authorization: Bearer eyJraWQiOiIxIiwiYWxnIjoiUlMyNTYifQ.eyJhYSI6ImJiIiwic3ViIjoiMTExMSIsImF1ZCI6IjExMSIsIm5iZiI6MTY4NDc0MjE2MCwic2NvcGUiOlsicGhvbmUiLCJvcGVuaWQiLCJwcm9maWxlIiwiZW1haWwiXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4ODg4IiwiZXhwIjoxNjg1MzQ2OTYwLCJpYXQiOjE2ODQ3NDIxNjB9.qsecTdwMCuTW3Lgg96lRx6gQmbPrqaYYPLXIqjYSNA1u7nDdTPRY-a3eqnEV0NvPkUyYRRLtwkESYl-EXfPWecJPI9JW_j-5tm5e14hRq8w2le6g5JThZBCnm8fs5-tKOtY-NaYPR_Sw0HXij3NFYAhGJ0winpMYJlF3dzpl3vgQq3kp0uRHsGJSXmwe1TV7twCkeIYOAheeL1tgzrRLxJFxHBRuSHly5go50XJOs7hS7XNoq5uq5dcSTMZa1qi5kxIXwvxKEMzpv72fgJgb3Gr93LRhzzMsaQBOFDeQR4zRh62mqYdtYuX1TrUph7rgrj2dd1YnDsumg5B9uYVkgA
